-- Esquema tal como lo generaba Hibernate con hbm2ddl=update.
-- En una base que ya tenia estas tablas, Flyway no corre este script (baseline en la version 1).

CREATE TABLE usuarios (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo   boolean NOT NULL,
    email    varchar(255),
    nombre   varchar(255),
    password varchar(255)
);

CREATE TABLE proveedores (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(255),
    nombre   varchar(255),
    telefono integer NOT NULL
);

CREATE TABLE productos (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       varchar(255),
    descripcion  varchar(255),
    disponible   boolean NOT NULL,
    nombre       varchar(255),
    preciocompra double precision NOT NULL,
    precioventa  double precision NOT NULL,
    stock        integer NOT NULL,
    stockminimo  integer NOT NULL
);

CREATE TABLE compras (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado       varchar(255) CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA')),
    fecha        date,
    proveedor_id integer REFERENCES proveedores (id),
    usuario_id   integer REFERENCES usuarios (id)
);

CREATE TABLE detalle_compras (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad       integer NOT NULL,
    preciounitario double precision NOT NULL,
    subtotal       double precision NOT NULL,
    compra_id      integer REFERENCES compras (id),
    producto_id    integer REFERENCES productos (id)
);
