-- Imagen de cada producto (una URL o una ruta del front, ej. img/productos/mou-001.svg)
ALTER TABLE productos ADD COLUMN imagenurl varchar(500);

-- Los productos de ejemplo usan las ilustraciones que vienen con el front
UPDATE productos SET imagenurl = 'img/productos/' || lower(codigo) || '.svg'
WHERE codigo IN ('MOU-001', 'TEC-001', 'MON-001', 'AUR-001', 'USB-064', 'SSD-480',
                 'RAM-008', 'CAM-001', 'RED-001', 'CAB-HD2', 'PAR-001', 'MPD-XL');

-- Reseñas: cada usuario puede dejar una por producto, con puntaje de 1 a 5 y un comentario
CREATE TABLE resenas (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id integer NOT NULL REFERENCES productos (id),
    usuario_id  integer NOT NULL REFERENCES usuarios (id),
    puntaje     integer NOT NULL,
    comentario  varchar(1000) NOT NULL DEFAULT '',
    fecha       timestamp NOT NULL,
    CONSTRAINT resenas_puntaje_check CHECK (puntaje BETWEEN 1 AND 5),
    CONSTRAINT resenas_una_por_usuario UNIQUE (producto_id, usuario_id)
);
CREATE INDEX resenas_producto_idx ON resenas (producto_id);
